@Finals_HostAddress = http://localhost:5040

POST {{Finals_HostAddress}}/api/users/register
Content-Type: application/json

###

POST {{Finals_HostAddress}}/api/users/login
Content-Type: application/json

###

GET {{Finals_HostAddress}}/api/products
Accept: application/json

###

GET {{Finals_HostAddress}}/api/products/{id}
Accept: application/json

###

GET {{Finals_HostAddress}}/api/users/
Accept: application/json

###

GET {{Finals_HostAddress}}/api/users/me
Accept: application/json

###

POST {{Finals_HostAddress}}/api/users/{email}/block
Content-Type: application/json

###

POST {{Finals_HostAddress}}/api/users/{email}/unblock
Content-Type: application/json

###

POST {{Finals_HostAddress}}/api/users/{email}/make-accountant
Content-Type: application/json

###

GET {{Finals_HostAddress}}/api/loans
Accept: application/json

###

GET {{Finals_HostAddress}}/api/loans/{id}
Accept: application/json

###

GET {{Finals_HostAddress}}/api/loans/pending
Accept: application/json

###

GET {{Finals_HostAddress}}/api/loans/declined
Accept: application/json

###

GET {{Finals_HostAddress}}/api/loans/accepted
Accept: application/json

###

GET {{Finals_HostAddress}}/api/loans/completed
Accept: application/json

###

POST {{Finals_HostAddress}}/api/loans/{id}/accept
Content-Type: application/json

###

POST {{Finals_HostAddress}}/api/loans/{id}/decline
Content-Type: application/json

###

POST {{Finals_HostAddress}}/api/loans/{id}/pay-monthly
Content-Type: application/json

###

DELETE {{Finals_HostAddress}}/api/loans/{id}
Accept: application/json

###

POST {{Finals_HostAddress}}/api/installmentloans/new-installment
Content-Type: application/json

###

PATCH {{Finals_HostAddress}}/api/installmentloans/{id}
Content-Type: application/json

###

POST {{Finals_HostAddress}}/api/fastloans/new-fast
Content-Type: application/json

###

PATCH {{Finals_HostAddress}}/api/fastloans/{id}
Content-Type: application/json

###

POST {{Finals_HostAddress}}/api/autoloans/new-auto
Content-Type: application/json

###

PATCH {{Finals_HostAddress}}/api/autoloans/{id}
Content-Type: application/json